language: ruby
bundler_args: --without development
script: bundle exec rake test_$DB
before_script: export JRUBY_OPTS="--server -Xcext.enabled=false -Xcompile.invokedynamic=false"
before_install:
  - gem update --system 2.1.11
  #- 'ruby -e "puts RUBY_VERSION" | grep ^1\.8 && gem update --system -v 2.1.11 || true'
rvm:
  - jruby
gemfile:
  - gemfiles/rails23.gemfile
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
env:
  - JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=mysql
  - JRUBY_OPTS="--1.9 $JRUBY_OPTS" DB=mysql PREPARED_STATEMENTS=false
  - JRUBY_OPTS="--1.9 $JRUBY_OPTS" DB=mysql PREPARED_STATEMENTS=true
  - JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=postgresql
  - JRUBY_OPTS="--1.9 $JRUBY_OPTS" DB=postgresql PREPARED_STATEMENTS=false INSERT_RETURNING=true
  - JRUBY_OPTS="--1.9 $JRUBY_OPTS" DB=postgresql PREPARED_STATEMENTS=true
  - JRUBY_OPTS="--1.9 $JRUBY_OPTS" DB=postgresql PREPARED_STATEMENTS=true INSERT_RETURNING=true
  - JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=sqlite3
  - JRUBY_OPTS="--1.9 $JRUBY_OPTS" DB=sqlite3
  - JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=derby
  - JRUBY_OPTS="--1.9 $JRUBY_OPTS" DB=derby PREPARED_STATEMENTS=true
  - JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=h2
  - JRUBY_OPTS="--1.9 $JRUBY_OPTS" DB=h2 PREPARED_STATEMENTS=true
  - JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=hsqldb
  - JRUBY_OPTS="--1.9 $JRUBY_OPTS" DB=hsqldb PREPARED_STATEMENTS=true
  - JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jndi
  - JRUBY_OPTS="--1.9 $JRUBY_OPTS" DB=jndi PREPARED_STATEMENTS=true
  # TODO: not sure why it can't connect :
  #- JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jdbc
  #- JRUBY_OPTS="--1.9 $JRUBY_OPTS" DB=jdbc
branches:
  only:
    - master
    - 1-2-stable
matrix:
  #allow_failures:
    #- gemfile: gemfiles/rails41.gemfile
  exclude:
    # Rails 4 prefers Ruby 2.0 (or at least >= 1.9.3) :
    - rvm: jruby
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=mysql
    - rvm: jruby
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=postgresql
    - rvm: jruby
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=sqlite3
    - rvm: jruby
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=derby
    - rvm: jruby
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=h2
    - rvm: jruby
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=hsqldb
    - rvm: jruby
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jndi
    - rvm: jruby
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jdbc
    # Rails 4.1 does not support Ruby 1.8 :
    - rvm: jruby
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=mysql
    - rvm: jruby
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=postgresql
    - rvm: jruby
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=sqlite3
    - rvm: jruby
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=derby
    - rvm: jruby
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=h2
    - rvm: jruby
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=hsqldb
    - rvm: jruby
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jndi
    - rvm: jruby
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jdbc
